version: "3.9"

services:
    db:
        image: postgres:15.4-alpine
        restart: always
        ports:
            - ${DB_PORT_EXTERNAL}:${DB_PORT}
        environment:
            - PGDATA=${DB_DATA_PATH}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
