FROM maven:3.8.5-openjdk-17-slim

WORKDIR /app

COPY ./pom.xml ./pom.xml

RUN mkdir ./common
COPY ./common/pom.xml ./common/pom.xml
COPY ./common/src ./common/src

RUN mkdir ./app
COPY ./app/pom.xml ./app/pom.xml
COPY ./app/src ./app/src

RUN mkdir ./gateway
COPY ./gateway/pom.xml ./gateway/pom.xml
COPY ./gateway/src ./gateway/src

RUN mvn dependency:go-offline -B
RUN mvn install -D maven.test.skip

COPY ./startup.sh ./startup.sh
RUN chmod +x ./startup.sh
