server:
    port: 8081
    servlet:
        context-path: "/api"
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true
        properties:
            hibernate:
                auto_quote_keyword: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                hbm2ddl:
                    auto: update # TODO set to none after setting up migrations
