server:
    port: ${GATEWAY_PORT}
    servlet:
        context-path: ${GATEWAY_PREFIX:/api}
spring:
    mvc:
        problemdetails:
            enabled: true
service:
    admin:
        username: admin
        password: password
    app:
        base-url: "http://${APP_HOST}:${APP_PORT}"
    auth-cookie:
        expire-duration: 86400
    jwt:
        expire-duration: 86400000
        secret: ${JWT_SECRET}
