server:
    port: ${API_FOOD_DELIVERY_PORT}
    servlet:
        context-path: ${API_FOOD_DELIVERY_PREFIX:/api}
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    flyway:
        create-schemas: true
        default-schema: public
        enabled: true
        locations: /db/migration/common
        validate-on-migrate: true
    jpa:
        show-sql: true
        properties:
            hibernate:
                auto_quote_keyword: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                hbm2ddl:
                    auto: none
    mvc:
        problemdetails:
            enabled: true
