FROM node:20.5-alpine3.17 as client-build

WORKDIR /app
COPY package*.json .
RUN npm ci --only=production
COPY . .

RUN npm run build

FROM nginx:1.25.2-alpine

COPY configs/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=client-build /app/build /usr/share/nginx/html
